import { AppState, EffortByPrjData, PjmCallback } from "global.slint";
import { Styles } from "styles.slint";

export component Header inherits Rectangle {
    in-out property <length> viewport_x;
    in property <[EffortByPrjData]> efforts;
    in property <[string]> weeks;

    height: Styles.height;
    HorizontalLayout {
        Rectangle {
            width: 60px * 4;
        }

        Flickable {
            viewport-x <=> root.viewport_x;
            HorizontalLayout {
                for data in weeks: Rectangle {
                //     background: data == root.efforts.current_week ? #ffff00 : Colors.green;
                     width: Styles.width;
                    Text {
                        text: data;
                        //color: black;
                    }
                }
            }
        }
    }
}
