import { AppState, EffortByPrjData } from "global.slint";
import { Styles } from "styles.slint";

export component LeftFooter inherits Rectangle {
    in property <[string]> weeks;

    in-out property <length> viewport_x;
    in property <[EffortByPrjData]> efforts;

    height: Styles.height * (max(AppState.model.length, AppState.worker_names.length) + 1);
    width: 60px * 4;

    HorizontalLayout {
        // I vari dev
        Rectangle {
            //width: Styles.width;
            VerticalLayout {
                for data in AppState.model: Rectangle {
                    height: Styles.height;
                    HorizontalLayout {
                        Rectangle {
                            background: data.col;
                            HorizontalLayout {

                                Text {
                                    width: Styles.width - 20px;
                                    font-weight: 800;
                                    color: data.text-color;
                                    text: data.title;
                                    horizontal-alignment: center;
                                    vertical-alignment: center;
                                }

                                Text {
                                    width: Styles.width - 20px;
                                    color: data.text-color;
                                    horizontal-alignment: center;
                                    vertical-alignment: center;
                                    text: "1";
                                }
                            }
                        }
                    }
                }
            }
        }

        // I vari worker
        Rectangle {
            VerticalLayout {
                for data in AppState.worker_names: Rectangle {
                    height: Styles.height;
                    Text {
                        width: Styles.width;
                        //color: black;
                        text: data;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }
        }
    }
}
