import { LineEdit, HorizontalBox, TextEdit } from "std-widgets.slint";
import { AppState, EffortByPrjData } from "global.slint";
import { Styles } from "styles.slint";
export component LeftColumn inherits Rectangle {
    in property <[EffortByPrjData]> efforts;

    in-out property <length> viewport_y;
    width: 60px * 4;

    Flickable {
        viewport-y <=> root.viewport_y;
        VerticalLayout {
            padding: 0px;
            spacing: 0px;
            for item in root.efforts: Rectangle {
                background: gray;
                HorizontalLayout {
                    TextEdit {
                        width: 60px * 2;
                        wrap: TextWrap.word-wrap;
                        horizontal-alignment: center;
                        text: item.text;
                        edited(text) => {
                            item.text = text;
                        }
                    }

                    VerticalLayout {
                        for data in AppState.model: Rectangle {
                            height: Styles.height * 2;
                            HorizontalLayout {
                                Rectangle {
                                    background: data.col;
                                    width: Styles.width - 50px;
                                    clip: true;
                                    Text {
                                        width: Styles.width - 50px;
                                        font-weight: 800;
                                        color: data.text-color;
                                        text: data.title;
                                        horizontal-alignment: center;
                                        vertical-alignment: center;
                                        wrap: word-wrap;
                                    }
                                }

                                VerticalLayout {
                                    LineEdit {
                                        height: Styles.height;
                                        width: Styles.width;
                                        horizontal-alignment: center;
                                    }

                                    Text {
                                        horizontal-alignment: center;
                                        vertical-alignment: center;
                                        height: Styles.height;
                                        text: "rem";
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
