import {
    AppState,
    EffortByPrjData,
    EffortByPrjGui,
    EffortsData,
    DayData,
    PjmCallback,
} from "global.slint";
import { Styles } from "styles.slint";
import { StyleMetrics, HorizontalBox } from "std-widgets.slint";

export component RightFooter inherits Rectangle {
    in property <EffortsData> efforts;
    in property <[DayData]> weeks;
    in-out property <length> viewport-x;

    Flickable {
        viewport-x <=> root.viewport-x;
        HorizontalLayout {
            padding: 0px;
            spacing: 0px;
            for data in weeks: Rectangle {
                HorizontalLayout {
                    Rectangle {
                        background: data.week == PjmCallback.this_week ? #00ce3a : Colors.transparent;
                        width: data.week == PjmCallback.this_week ? PjmCallback.this_week_width : 0px;
                    }

                    VerticalLayout {
                        for name[index] in efforts.worker_names: Rectangle {
                            background: index.mod(2) == 0 ? Colors.gray : Colors.transparent;
                            width: Styles.width;
                            height: Styles.height;
                            Text {
                                text: 0;
                            }
                        }
                    }
                }
            }
        }
    }
}
